{% set name = "opentelemetry-instrumentation-openai-agents" %}
{% set version = "0.62.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ac1d630dfe7ed76f5ad6f756f78ce99532eb8f2ac5c178de63b54dd25b6f57fe

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
    - opentelemetry-semantic-conventions >=0.63b1
  run_constrained:
    - openai-agents >=0.14.2

test:
  imports:
    - opentelemetry.instrumentation.openai_agents
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry OpenAI instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library enables tracing of agentic workflows implemented using the OpenAI Agents framework,
    allowing visibility into agent reasoning, tool usage, and decision-making steps.

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - reachable_url
    - missing_imports_or_run_test_py
